language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"

services:
 - mysql

before_install:
 - mysql -u root -e 'CREATE DATABASE crudapi_test;'
 - mysql -u root -e 'GRANT ALL ON crudapi_text TO "travis'@'localhost";'
 - mysql -u root -e 'GRANT ALL ON crudapi_text TO "travis'@'%";'

install:
  - composer install
  - composer dumpautoload
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed
  - php artisan user:role --email=testadmin@example.com --role=Administrator

script: ./vendor/bin/phpunit --coverage-text
